[package]
name = "virtual-cpu-gbz80"
version = "0.1.0"
authors = ["Danielle Brook-Roberge <danielle@brook-roberge.ca>"]
edition = "2018"

[dependencies]
virtual-cpu-core = { path = "../virtual-cpu-core" }
virtual-cpu-8080 = { path = "../virtual-cpu-8080" }